services:
  postgresql:
    image: "postgres:17.2"
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
      - microblog-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} 
  redis:
    image: "redis:latest"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "pdoing" ]
    ports:
      - "6379:6379"
    networks:
      - microblog-network