# PUBLIC: DO NOT ADD SECRETS

role_arn = "${AWS_ROLE_ARN}"
AWS_REGION = "${AWS_REGION}"

MAIL_PORT = "${MAIL_PORT}"
MAIL_USERNAME = "${MAIL_USERNAME}"
MAIL_PASSWORD = "${MAIL_PASSWORD}"
MAIL_SERVER = "${MAIL_SERVER}"
DATABASE_URL = "${DATABASE_URL}"
SECRET_KEY = "${SECRET_KEY}"
REDIS_URL = "${REDIS_URL}"

# PUBLIC: DO NOT ADD SECRETS