"""search vector as tsvector column

Revision ID: 35f584c9201c
Revises: f4accde8ec2c
Create Date: 2024-12-14 17:37:34.987182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f584c9201c'
down_revision = 'f4accde8ec2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector(CAST('english' AS REGCONFIG), CAST(body AS TEXT))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector('english'::regconfig, body::text)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
