"""search vector as mapped column

Revision ID: b92d17383cae
Revises: c5ab407e8724
Create Date: 2024-12-14 17:08:39.425761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92d17383cae'
down_revision = 'c5ab407e8724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector(CAST('english' AS REGCONFIG), CAST(coalesce(body, '') AS TEXT))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector('english'::regconfig, COALESCE(body, ''::character varying)::text)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
