"""search_vector column in posts

Revision ID: f4accde8ec2c
Revises: b92d17383cae
Create Date: 2024-12-14 17:21:16.108938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4accde8ec2c'
down_revision = 'b92d17383cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector(CAST('english' AS REGCONFIG), CAST(body AS TEXT))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_search_vector', postgresql_using='gin')
        batch_op.create_index('ix_post_search_vector', [sa.text("to_tsvector('english'::regconfig, COALESCE(body, ''::character varying)::text)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
